# Generated by Django 2.1.3 on 2018-12-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='math',
            name='dzialanie',
        ),
        migrations.AddField(
            model_name='math',
            name='operation',
            field=models.CharField(default='add', max_length=10),
            preserve_default=False,
        ),
    ]
